import { defineNuxtModule, createResolver, addPlugin, extendViteConfig, useLogger, addServerHandler, addTemplate } from '@nuxt/kit'
import { createHash } from 'node:crypto'
import { defu } from 'defu'
import { resolve } from 'node:path'
import fsDriver from 'unstorage/drivers/fs'
import { createStorage } from 'unstorage'

interface ModuleOptions {
  devStorage?: boolean
  auth?: {
    github?: {
      clientId: string
      clientSecret: string
    }
  }
  repository?: {
    /**
     * @default 'github'
     */
    provider?: 'github'
    owner: string
    repo: string
    /**
     * @default 'main'
     */
    branch?: string
    /**
     * @default ''
     */
    rootDir?: string
  }
}

const logger = useLogger('nuxt-studio')
export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-studio',
    configKey: 'contentStudio',
  },
  defaults: {
    devStorage: false,
  },
  async setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)
    const runtime = (...args: string[]) => resolver.resolve('./runtime', ...args)
    options = defu(options, {
      repository: {
        provider: 'github',
        branch: 'main',
        rootDir: '',
      },
      auth: {
        github: {
          clientId: process.env.STUDIO_GITHUB_CLIENT_ID,
          clientSecret: process.env.STUDIO_GITHUB_CLIENT_SECRET,
        },
      },
    }) as ModuleOptions

    if (!nuxt.options.dev && !nuxt.options._prepare) {
      if (!options.auth?.github?.clientId && !options.auth?.github?.clientSecret) {
        logger.warn([
          'Nuxt Content Studio relies on GitHub OAuth to authenticate users.',
          'Please set the `STUDIO_GITHUB_CLIENT_ID` and `STUDIO_GITHUB_CLIENT_SECRET` environment variables.',
        ].join(' '))
      }
    }

    nuxt.options.runtimeConfig.public.contentStudio = {
      studioDevStorage: (nuxt.options.dev && options.devStorage) || false,
      studioDevServer: process.env.STUDIO_DEV_SERVER,
      // @ts-expect-error Autogenerated type does not match with options
      repository: options.repository,
    }

    nuxt.options.runtimeConfig.contentStudio = {
      auth: {
        sessionSecret: createHash('md5').update([
          options.auth?.github?.clientId,
          options.auth?.github?.clientSecret,
        ].join('')).digest('hex'),
        // @ts-expect-error todo fix github type issue
        github: options.auth?.github,
      },
    }

    addPlugin(process.env.STUDIO_DEV_SERVER
      ? runtime('./plugins/studio.client.dev')
      : runtime('./plugins/studio.client'))

    nuxt.options.vite = defu(nuxt.options.vite, {
      vue: {
        template: {
          compilerOptions: {
            isCustomElement: (tag: string) => {
              return tag === 'nuxt-studio'
            },
          },
        },
      },
    })
    extendViteConfig((config) => {
      config.optimizeDeps ||= {}
      config.optimizeDeps.include = [
        ...(config.optimizeDeps.include || []),
        'debug',
        'extend',
      ]
    })

    if (nuxt.options.dev && options.devStorage) {
      nuxt.options.runtimeConfig.public.contentStudio.studioDevStorage = true

      nuxt.options.nitro.storage = {
        ...nuxt.options.nitro.storage,
        nuxt_content_studio: {
          driver: 'fs',
          base: resolve(nuxt.options.rootDir, 'content'),
        },
      }
      addServerHandler({
        route: '/__nuxt_content/studio/dev/fs/**',
        handler: runtime('./server/routes/dev/fs/[...path]'),
      })
    }

    const assetsStorage = createStorage({
      driver: fsDriver({
        base: resolve(nuxt.options.rootDir, 'public'),
      }),
    })
    assetsStorage.getKeys()
      .then((keys) => {
        addTemplate({
          filename: 'content-studio-public-assets.mjs',
          getContents: () => {
            return [
              'import { createStorage } from \'unstorage\'',
              'const storage = createStorage({})',
              '',
              ...keys.map((key) => {
                const value = {
                  id: `public-assets/${key.replace(/:/g, '/')}`,
                  extension: key.split('.').pop(),
                  stem: key.split('.').join('.'),
                  path: '/' + key.replace(/:/g, '/'),
                }
                return `storage.setItem('${value.id}', ${JSON.stringify(value)})`
              }),
              '',
              'export const publicAssetsStorage = storage',
            ].join('\n')
          },
        })
      })
      .catch((error) => {
        console.error(error)
      })

    addServerHandler({
      route: '/__nuxt_content/studio/auth/github',
      handler: runtime('./server/routes/auth/github.get'),
    })
    addServerHandler({
      route: '/__nuxt_content/studio/auth/session',
      handler: runtime('./server/routes/auth/session.get'),
    })
    addServerHandler({
      method: 'delete',
      route: '/__nuxt_content/studio/auth/session',
      handler: runtime('./server/routes/auth/session.delete'),
    })
    addServerHandler({
      route: '/__nuxt_content/studio',
      handler: runtime('./server/routes/admin'),
    })
    addServerHandler({
      route: '/sw.js',
      handler: runtime('./server/routes/sw'),
    })
    // addServerHandler({
    //   route: '/__nuxt_content/studio/auth/google',
    //   handler: runtime('./server/routes/auth/google.get'),
    // })
  },
})
