import { defineNuxtModule, createResolver, addPlugin, extendViteConfig, useLogger, addServerHandler, addTemplate, addVitePlugin } from '@nuxt/kit'
import { createHash } from 'node:crypto'
import { defu } from 'defu'
import { resolve } from 'node:path'
import fsDriver from 'unstorage/drivers/fs'
import { createStorage } from 'unstorage'
import type { ViteDevServer } from 'vite'
import { getAssetsStorageDevTemplate, getAssetsStorageTemplate } from './templates'

interface ModuleOptions {
  devStorage?: boolean
  auth?: {
    github?: {
      clientId: string
      clientSecret: string
    }
  }
  repository?: {
    /**
     * @default 'github'
     */
    provider?: 'github'
    owner: string
    repo: string
    /**
     * @default 'main'
     */
    branch?: string
    /**
     * @default ''
     */
    rootDir?: string
  }
}

const logger = useLogger('nuxt-studio')
export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'nuxt-studio',
    configKey: 'contentStudio',
  },
  defaults: {
    devStorage: true,
  },
  async setup(options, nuxt) {
    const resolver = createResolver(import.meta.url)
    const runtime = (...args: string[]) => resolver.resolve('./runtime', ...args)
    options = defu(options, {
      repository: {
        provider: 'github',
        branch: 'main',
        rootDir: '',
      },
      auth: {
        github: {
          clientId: process.env.STUDIO_GITHUB_CLIENT_ID,
          clientSecret: process.env.STUDIO_GITHUB_CLIENT_SECRET,
        },
      },
    }) as ModuleOptions

    if (!nuxt.options.dev && !nuxt.options._prepare) {
      if (!options.auth?.github?.clientId && !options.auth?.github?.clientSecret) {
        logger.warn([
          'Nuxt Content Studio relies on GitHub OAuth to authenticate users.',
          'Please set the `STUDIO_GITHUB_CLIENT_ID` and `STUDIO_GITHUB_CLIENT_SECRET` environment variables.',
        ].join(' '))
      }
    }

    nuxt.options.runtimeConfig.public.contentStudio = {
      studioDevStorage: (nuxt.options.dev && options.devStorage) || false,
      studioDevServer: process.env.STUDIO_DEV_SERVER,
      // @ts-expect-error Autogenerated type does not match with options
      repository: options.repository,
    }

    nuxt.options.runtimeConfig.contentStudio = {
      auth: {
        sessionSecret: createHash('md5').update([
          options.auth?.github?.clientId,
          options.auth?.github?.clientSecret,
        ].join('')).digest('hex'),
        // @ts-expect-error todo fix github type issue
        github: options.auth?.github,
      },
    }

    addPlugin(process.env.STUDIO_DEV_SERVER
      ? runtime('./plugins/studio.client.dev')
      : runtime('./plugins/studio.client'))

    nuxt.options.vite = defu(nuxt.options.vite, {
      vue: {
        template: {
          compilerOptions: {
            isCustomElement: (tag: string) => {
              return tag === 'nuxt-studio'
            },
          },
        },
      },
    })
    extendViteConfig((config) => {
      config.optimizeDeps ||= {}
      config.optimizeDeps.include = [
        ...(config.optimizeDeps.include || []),
        'debug',
        'extend',
      ]
    })

    if (nuxt.options.dev && options.devStorage) {
      nuxt.options.runtimeConfig.public.contentStudio.studioDevStorage = true

      nuxt.options.nitro.storage = {
        ...nuxt.options.nitro.storage,
        nuxt_studio_content: {
          driver: 'fs',
          base: resolve(nuxt.options.rootDir, 'content'),
        },
        nuxt_studio_public_assets: {
          driver: 'fs',
          base: resolve(nuxt.options.srcDir, 'public'),
        },
      }
      addServerHandler({
        route: '/__nuxt_content/studio/dev/content/**',
        handler: runtime('./server/routes/dev/content/[...path]'),
      })
      addServerHandler({
        route: '/__nuxt_content/studio/dev/public/**',
        handler: runtime('./server/routes/dev/public/[...path]'),
      })
    }

    const assetsStorage = createStorage({
      driver: fsDriver({
        base: resolve(nuxt.options.rootDir, 'public'),
      }),
    })
    addTemplate({
      filename: 'content-studio-public-assets.mjs',
      getContents: () => nuxt.options.dev
        ? getAssetsStorageDevTemplate(assetsStorage, nuxt)
        : getAssetsStorageTemplate(assetsStorage, nuxt)
    })

    addVitePlugin({
      name: 'nuxt-studio',
      configureServer: (server: ViteDevServer) => {
        assetsStorage.watch((type, file) => {
          server.ws.send({
            type: 'custom',
            event: 'nuxt-studio:media:update',
            data: { type, id: `public-assets/${file}` },
          })
        })
      }, 
      closeWatcher: () => { assetsStorage.unwatch() },
    })

    addServerHandler({
      route: '/__nuxt_content/studio/auth/github',
      handler: runtime('./server/routes/auth/github.get'),
    })
    addServerHandler({
      route: '/__nuxt_content/studio/auth/session',
      handler: runtime('./server/routes/auth/session.get'),
    })
    addServerHandler({
      method: 'delete',
      route: '/__nuxt_content/studio/auth/session',
      handler: runtime('./server/routes/auth/session.delete'),
    })
    addServerHandler({
      route: '/__nuxt_content/studio',
      handler: runtime('./server/routes/admin'),
    })
    addServerHandler({
      route: '/sw.js',
      handler: runtime('./server/routes/sw'),
    })
    // addServerHandler({
    //   route: '/__nuxt_content/studio/auth/google',
    //   handler: runtime('./server/routes/auth/google.get'),
    // })
  },
})
